### PR TITLE
Feature : Add toggle button for Dark Mode

### LINKED ISSUE #2: Feature Request : Add dark mode toggle button ! 🔆
**Is your feature request related to a problem? Please describe.**

Toggle button for dark mode!

**Describe the solution you'd like**

Similar to : https://ryanfeigenbaum.com/dark-mode/

image

**Describe alternatives you've considered**

Example is just for representation, new ideas are welcome!

**Additional context**

Examples : 

1. https://codepen.io/demilad/pen/bZRjpb
2. https://hacktoberfest.digitalocean.com/hacktoberfest-update

### PR DESCRIPTION
**Pull request by paramaDEV**
Hi, this is my first contribution in Hacktoberfest 2020.

I just added a toggle button to switch light mode to dark mode. I hope you  interested.

### CODE REVIEW

**Comment by abhisheksurve45** [comment]
Hey @paramaDEV , thank you so much for showing interest in my repository, I'm satisfied with your work, however have 2 suggestions. Can you please go over them

1. Placing the toggle at top right corner

2. No js alerts are required on toggle, we can simply show `Toggle` tooltip on hover.

image

Thanks again for contributing!

**Comment by paramaDEV** [comment]
Okey sir. I can do it

Pada tanggal Jum, 9 Okt 2020 22.38, Abhishek Surve <notifications@github.com>
menulis:

**Comment by abhisheksurve45** [comment]
Changes look good to me @paramaDEV , had a question though, is it possible to make the dark and light mode with transition effect? Also the mode can be saved in local storage for further reloads.

Link : https://henryegloff.com/how-to-code-a-simple-dark-mode-toggle/

This isn't a blocker though, I'm accepting your pull request. Will merge it later upon your confirmation. 

Thanks again for contributing!

**Comment by paramaDEV** [comment]
Thank you so much sir.

Pada tanggal Sab, 10 Okt 2020 16.04, Abhishek Surve <
notifications@github.com> menulis:

**Pull request merged**
